language: node_js
sudo: true
before_cache:
  - brew cleanup
cache:
  directories:
  - node_modules
  - "/usr/local/Cellar"
  - $HOME/Library/Caches/Homebrew

node_js:
- '11'
addons:
  apt:
    packages:
      - fakeroot
before_script:
- if [[ -n "$TRAVIS_TAG" ]]; then cp ./.travis/phore.pvk ./.travis/phore.keyfile; fi
- if [[ -n "$TRAVIS_TAG" ]]; then openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in .travis/cert.p12.enc -d -a -out ./.travis/cert.p12; fi
- if [[ -n "$TRAVIS_TAG" ]]; then openssl aes-256-cbc -k "$PHORE_SECRET" -in .travis/phore.cert.spc.enc -d -a -out ./.travis/phore.cert.spc; fi
- if [[ -n "$TRAVIS_TAG" ]]; then if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "./.travis/add-key.sh"; fi ; fi
jobs:
  include:
      - os: osx
        osx_image: xcode11
        env: BINARY=osx
      - os: osx
        osx_image: xcode11
        env: BINARY=osxclient
      - os: linux
      - os: osx
        osx_image: xcode11.2
        env: BINARY=win
script:
- npm run lint
- npm run test
- if [ -n "$TRAVIS_TAG" ]; then ./build.sh; fi
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
    - "dist/win64/RELEASES"
    - "dist/win64/*.exe"
    - "dist/win64/*.nupkg"
    - "dist/osx/*.dmg"
    - "dist/osx/*.zip"
    - "dist/linux32/*.deb"
    - "dist/linux64/*.deb"
    - "dist/linux32/*.rpm"
    - "dist/linux64/*.rpm"
  skip_cleanup: true
  all_branches: true
  on:
    tags: true
env:
  global:
  - secure: udFem4PbHoVMJzp/bDgE2x+/3uY+c9llv4RMkVRru3Y/QaVjVg6c1K2uovmUhdmo0/YjzlOhGlHHpA/klxHy5Yc7Ba3cahlnaugMeCHWEUnOuX2BwzFc051PPce5SpKqLGZTHSK8PQtFYiuirgnaN8Y3YZ1R7h4lfiFVHN76KYVmB+nFojaykYA0tnZKT/wWQnsE6H/+ApxAHTPKjAktUbc2a5ojrdj84I+fWYstDm72u3ykRiUilJVA8WJ8tnuhTenNoGkzNda4pbyKcEe2UnswhEOukDuYn6V34ifYFx3uWlS9laRjsmNudaNmiLIw1Gx5l5IVgy1/QBWBAfJCmgq8Shs0FjbI87uvU0w4D8k92dp2wC6MKtFuiMbVb/1xBnV5h8dtfO/oE1/xHX4xBRiJdosLeyO8C3sRRIi36QQJS4HE7D+AJ0pbjxjuJuJir2gAldo+YnRpD2yZY8eOgmttOZuD5g9CZpRF4J0lru/HOgDGJ48NCr99/069dzGtV2QCMwhIrVU7rDVqI/fub5cZW9KQHOMd0oDHjEHv87WSPF7s6/XmPsHFaBNQLsVvoe3WDrZ0AMiTFbyH0tdVO3so+lB00b3RBM8GsqTIJ9GO61rAnmir7iCYjOW1PlT/0O3s4aGde2LP0UwqO23MwvTmE7LMNlXhbHhn9OY5QPY=
  - WINEDLLOVERRIDES="mscoree,mshtml="
  - WINEDEBUG="-all"
